# ----------------------------------------------------------
# The name of the workflow
# ----------------------------------------------------------
name: cicd

# ----------------------------------------------------------
# The event that triggers this workflow
# ----------------------------------------------------------
on:
  push:
    branches:
      - main

# ----------------------------------------------------------
# The jobs that this workflow will run
# ----------------------------------------------------------
jobs:
  unit-tests:
    runs-on: ubuntu-latest

    # ----------------------------------------------------------
    # The steps that this job will execute
    # ----------------------------------------------------------
    steps:
    - name: Run unit tests
      run: |
        python3 -m unittest test_game.py
